### ISSUE TITLE
Is it possible to connect to redshift Serverless using redshift_connector?

### ISSUE THREAD

**Issue by seanyboi** [aws/amazon-redshift-python-driver#106]
Is it possible to connect to redshift Serverless using this connecter? If so please update documentation to show how.

**Comment by Brooke-white** [comment]
Hi @seanyboi,

Yes, we have a [tutorial showing this](https://github.com/aws/amazon-redshift-python-driver/blob/master/tutorials/001%20-%20Connecting%20to%20Amazon%20Redshift.ipynb). Thank you for the feedback, we will work with the Amazon doc team to add an example to the official Python driver docs as well.

**Comment by seanyboi** [comment]
That's great to hear thank you. I managed to connect and pull data using the `boto3.client("redshift-data")`  data api. Do you recommend using redshift_connector or boto3? 😄

**Comment by Brooke-white** [comment]
very cool! I'm a bit biased since I work on redshift_connector :), but I'd say that depends on what the requirements of your project are. I'd recommend to take a look at the docs for both projects, play around with them both a bit, and think a bit about the following questions
- How will users need to authenticate? IAM? Identity Providers (e.g. Azure, Okta)? Are there any project/company requirements that need to be considered? 
- If your project/team/company is already accessing Redshift through other means, is there anyway the authentication setup that is configured (e.g. IAM or Identity Provider) could be reused with redshift-data or redshift_connector?
- How do you prefer to execute statements and retrieve data?
- What will you do with the data retrieved from Redshift? Does data need to be passed off to another tool or library?
- What does the existing workflow look like? How would each tool integrate with that?

For redshift-data client I'd recommend to read some of their docs to get a better idea of what authentication and statement execution looks like. [This blog post](https://aws.amazon.com/blogs/big-data/using-the-amazon-redshift-data-api-to-interact-with-amazon-redshift-clusters/#:~:text=Run%20SQL%20commands,-You%20can%20run%20SELECT%2C) gives a nice overview of how statement execution looks. Also, you can check out the [redshift-data client GitHub repository](https://github.com/aws-samples/getting-started-with-amazon-redshift-data-api) to see some of the tutorials, docs, etc. they're provided.

For redshift_connector I'd recommend to checkout a few of the blog post the team has written
- [Integration with Okta Identity Provider](https://aws.amazon.com/blogs/big-data/federated-api-access-to-amazon-redshift-using-an-amazon-redshift-connector-for-python/)
- [Integration with SQLAlchemy](https://aws.amazon.com/blogs/big-data/use-the-amazon-redshift-sqlalchemy-dialect-to-interact-with-amazon-redshift/)

as well as checking out our [tutorials](https://github.com/aws/amazon-redshift-python-driver/tree/master/tutorials) and [integrations we have with other data tooling projects](https://github.com/aws/amazon-redshift-python-driver#integrations). As always, we are always looking to improve so please let us know if there's something missing that you'd like to see, or any thing else I can help with :)

**Comment by seanyboi** [comment]
wow! thanks Brooke, this is the most in depth response I've ever had on an open source project. I shall checkout all this information and if I have an improvements I shall let you know :) thank you very much!

**Comment by seanyboi** [comment]
so been playing around with it - but I keep getting `('communication error', gaierror(8, 'nodename nor servname provided, or not known'))`  when running:

```python
    with redshift_connector.connect(
        host="xxxxxxxxxxxxxxx.us-east-2.redshift-serverless.amazonaws.com",
        user="",
        password="",
        database="",
    ) as conn:
```

So to confirm when I am on the redshift serverless console:

* the `host` is the endpoint without the port and database table name attached?
* the `user` is the admin user name you see on the console?
* the `password` is the admin password?
* the `database` is the database name you see on the console?

**Comment by Brooke-white** [comment]
> the host is the endpoint without the port and database table name attached?

Correct, this may look something like this `0123456789123.us-east-2.redshift-serverless.amazonaws.com`

> the user is the admin user name you see on the console?

Correct, it can be that user or any other user with the desired permissions (you can query possible users by looking to the `pg_user` table)

> the password is the admin password?

Correct, assuming the authenticating user is the admin user.

> the database is the database name you see on the console?

Correct

My guess is that you could be running into connectivity issues due to the Redshift serverless endpoint running in a non-publicly accessible VPC. What this means is that the Redshift serverless endpoint by default created in a subnet of the VPC that blocks incoming traffic from *outside* of the VPC (such as the connection attempt from your machine) 

[This is mentioned here in the Connecting to Amazon Redshift Serverless docs](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-connecting.html). 

There are a couple different approaches I know of to approach this
1. Use a Redshift-managed VPC endpoint
2. Use a Network Load Balancer

Some details about how to take these approaches can be found at the bottom of the doc I linked above.

**Comment by Brooke-white** [comment]
Another thing to check is that the Redshift serverless cluster is not paused or stopped

**Comment by Brooke-white** [comment]
please re-open this, or a new issue if you need any more help with connecting to redshift serverless
