### ISSUE TITLE
Error handling after invalid query

### ISSUE THREAD

**Issue by romgrk** [aws/amazon-redshift-python-driver#113]
## Driver version
Unsure

## Redshift version
Version: `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38698`

## Client Operating System
Various

## Python version
Version: `3.7`

## Table schema
Irrelevant

## Problem description
After sending an invalid query to the database, all subsequent queries fail with the following error message:
```
{"detail":"Query error: {'S': 'ERROR', 'C': '25P02', 'M': 'current transaction is aborted, commands ignored until end of transaction block', 'F': '../src/pg/src/backend/tcop/postgres.c', 'L': '3384', 'R': 'exec_parse_message'}"}
```

How is it possible to reset the connection so subsequent valid queries don't fail?

## Reproduction code
```python
    def _execute_query(self, sql: str) -> pd.DataFrame:
        with self._redshift_client_connection.cursor() as cursor:
            cursor.execute(sql)
            result = cursor.fetch_dataframe()
            return result
```
And later
```
_execute_query('invalid query')
```

**Comment by Brooke-white** [comment]
hey @romgrk , you need to `rollback` following the invalid query. More on [rollback](https://docs.aws.amazon.com/redshift/latest/dg/r_ROLLBACK.html) can be read here. Please let me know if you have any questions.

**Comment by Brooke-white** [comment]
to rollback using redshift_connector: `self._redshift_client_connection.rollback()` or `cursor.execute('rollback')`

please note, that if you're making changes to the database (e.g. inserting data, creating/dropping tables/schemas, etc.), using rollback will wipe out all of the changes you've made since opening the connection. So you'd want to use `self._redshift_client_connection.autocommit = True` or manually commit using `self._redshift_client_connection.commit()` or `cursor.execute('commit')` per your preference/use case.

**Comment by romgrk** [comment]
Ok, thanks.
