### ISSUE TITLE
redshift_connector.error.ProgrammingError when running AnalyzeVacuumUtility

### ISSUE THREAD

**Issue by avishwakarma-tunein** [aws/amazon-redshift-python-driver#140]
## Driver version
2.0.908, 2.0.909

## Redshift version
`PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.43931`

## Client Operating System
[Docker Image python:3.8-slim](https://github.com/awslabs/amazon-redshift-utils/blob/master/Dockerfile)

## Python version
python 3.8

## Problem description
1. Expected behaviour:
I am trying to run the [AnalyzeVacuumUtility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/AnalyzeVacuumUtility) using docker like this:
```
docker run --net host --rm -it --env-file redshift.env amazon-redshift-utils analyze-vacuum
```
The `redshift.env` file simply contains user/password/host so that it can connect to Redshift.

expected the utility to connect to redshift and list the tables it needed to analyse

3. Actual behaviour:
It errors out immediately with a cryptic error message.

5. Error message/stack trace:
```
Running analyze-vacuum utility
Traceback (most recent call last):
  File "/home/ubuntu/amazon-redshift-utils/.venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1631, in execute
    ps = cache["ps"][key]
KeyError: ("set search_path = '$user',public, public, ci_pr/105_public, ci_pr/104_public, analyst_new_schema_public, ci_pr/140_public, public_the_best, public_integration_test, public_utils, public_logs_internal, public_public, public_logs", ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 125, in <module>
    main()
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 116, in main
    result = analyze_vacuum.run_analyze_vacuum(**args)
  File "/home/ubuntu/amazon-redshift-utils/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 682, in run_analyze_vacuum
    master_conn = get_rs_conn(kwargs[config_constants.DB_HOST],
  File "/home/ubuntu/amazon-redshift-utils/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 110, in get_rs_conn
    aws_utils.set_search_paths(conn, schema_name, exclude_external_schemas=True)
  File "/home/ubuntu/amazon-redshift-utils/src/AnalyzeVacuumUtility/../redshift_utils_helper.py", line 77, in set_search_paths
    c.execute(search_path)
  File "/home/ubuntu/amazon-redshift-utils/.venv/lib/python3.8/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/ubuntu/amazon-redshift-utils/.venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1701, in execute
    self.handle_messages(cursor)
  File "/home/ubuntu/amazon-redshift-utils/.venv/lib/python3.8/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "/"', 'P': '48', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}
```
6. Any other details that can be helpful:

## Python Driver trace logs
- can provide if needed

## Reproduction code
[link to where exception occured](https://github.com/awslabs/amazon-redshift-utils/blob/6fa44c8d393aa672624f4f527ea45c67713c1cb9/src/redshift_utils_helper.py#L48)

**Comment by Brooke-white** [comment]
Hey @avishwakarma-tunein , thanks for reaching out. this is an interesting error, I'd be interested to see the query that's been issued.

```
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "/"', 'P': '48', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}
```

tells me that when Redshift server received the query it is finding some sort of syntax error in it, which means either AnalyzeVacuumUtility has written an incorrect query or that redshift-connector malforms the query somehow. Given the link where the exception occurs show we just send a query string (without separate parameters) to the server, my guess is the query is malformed 

I'm not familiar with AnalyzeVacuumUtility, but see they have some debug setting: https://github.com/awslabs/amazon-redshift-utils/blob/6fa44c8d393aa672624f4f527ea45c67713c1cb9/src/redshift_utils_helper.py#L73 if you could enable this it could help us see where this issue is originating as it prints the query.

From there, I'd recommend to grab that query string and (if possible on your end) try to issue is via Redshift Query Editor or PSQL CLI to see if those client tools complain about it to. If so, I'd take that as confirmation that something is wrong in the query.
