### ISSUE TITLE
Get column views returns empty list always

### ISSUE THREAD

**Issue by Yarden-zamir** [aws/amazon-redshift-python-driver#147]
## Driver version

redshift_connector==2.0.910

## Redshift version
select version();
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.46987

## Client Operating System
macos
ubunto-latest (github actions)

## Python version

3.11
## Table schema

Can't share that

## Problem description

1. Expected behaviour: I have a few views, when quering them I expect to get them
2. Actual behaviour: I don't get them
3. Error message/stack trace:
4. Any other details that can be helpful:

## Reproduction code

```python
cols = [col[3] for col in self.connection.cursor().get_columns(schema_pattern=schema_name, tablename_pattern=table_name) if col[3]]
```
returns empty list for views columns

## Current workaround that works for us (same schema name and table_name)
```python
select * from SVV_COLUMNS where table_schema = '{schema_name}' and table_name = '{table_name}'
```
returns list of view columns

**Comment by Brooke-white** [comment]
Hey @Yarden-zamir ,

Thank you for opening this issue. The team will investigate this. In the meantime, I have a few questions:

1. Have you tried to use this method with another Redshift driver (e.g. ODBC, JDBC)? Did you see issue? Which version?
3. Can you share any more details about your Table? Is the schema internal/external/not provided?
4. If possible, providing an example Table schema where the issue is seen would expedite this investigation e.g. `create table my_test (c1 int, c2 timetz)`

**Comment by Brooke-white** [comment]
Hi @Yarden-zamir , checking in to see if you're still facing this issue and if you can provide any more details to aid the investigation. The team has not been able to reproduce this so far.

**Comment by Brooke-white** [comment]
closing as we haven't heard back. Please reopen if you continue to experience this issue.
