### ISSUE TITLE
Materialized view creation fails using parameters

### ISSUE THREAD

**Issue by ajisaka** [aws/amazon-redshift-python-driver#148]
## Driver version

redshift-connector==2.0.910

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.46987

## Client Operating System

Arch Linux on WSL (Windows 10 - version: 22H2, build: 19045.2604)

## Python version

3.9.13

## Problem description

Using parameters when creating a Materialized View can cause the creation to fail. However, if no parameters are used, the creation will succeed even if the statements are the same.

## Python Driver trace logs

```
Traceback (most recent call last):
  File "/home/ajisaka/temp/pyred/test.py", line 30, in <module>
    main()
  File "/home/ajisaka/temp/pyred/test.py", line 24, in main
    cur.execute(f'CREATE MATERIALIZED VIEW ng AS ({definition})', (100,))
  File "/home/ajisaka/temp/pyred/.venv/lib/python3.9/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/ajisaka/temp/pyred/.venv/lib/python3.9/site-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/home/ajisaka/temp/pyred/.venv/lib/python3.9/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'Materialized view could not be created.', 'F': '../src/mv/mv_ddl.cpp', 'L': '1795', 'R': 'DefineMatView'}
```

## Reproduction code

```python
import redshift_connector

from os import environ

def main() -> None:
    conn = redshift_connector.connect(
        database='dwh',
        host='localhost',
        port=5439,
        password=environ['PGPASSWORD'],
        user='admin'
    )

    with conn.cursor() as cur:
        cur.execute('DROP TABLE sample CASCADE')
        cur.execute('CREATE TABLE sample (name TEXT, age INTEGER)')
        definition = 'SELECT * FROM sample WHERE age = %s'

        # This line does not raise any errors
        cur.execute(f'CREATE MATERIALIZED VIEW ok AS ({definition})'.replace('%s', '100'))

        # BUT this line raises an error
        cur.execute(f'CREATE MATERIALIZED VIEW ng AS ({definition})', (100,))
        # redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'Materialized view could not be created.', 'F': '../src/mv/mv_ddl.cpp', 'L': '1795', 'R': 'DefineMatView'}

    conn.commit()

if __name__ == '__main__':
    main()
```

This `localhost:5439` is an SSH tunnel to the Redshift host on AWS.

## But, using psycopg2 succeeds

``` python
import psycopg2

from os import environ

def main() -> None:
    conn = psycopg2.connect(
        database='dwh',
        host='localhost',
        port=5439,
        password=environ['PGPASSWORD'],
        user='admin'
    )

    with conn.cursor() as cur:
        cur.execute('DROP TABLE sample CASCADE')
        cur.execute('CREATE TABLE sample (name TEXT, age INTEGER)')
        definition = 'SELECT * FROM sample WHERE age = %s'

        cur.execute(f'CREATE MATERIALIZED VIEW ok AS ({definition})'.replace('%s', '100'))
        cur.execute(f'CREATE MATERIALIZED VIEW ng AS ({definition})', (100,))

    conn.commit()

if __name__ == '__main__':
    main()
```

## Package versions

psycopg2==2.9.5

``` shell
$ pip freeze
asn1crypto==1.5.1
beautifulsoup4==4.11.2
boto3==1.26.88
botocore==1.29.88
certifi==2022.12.7
charset-normalizer==3.1.0
idna==3.4
jmespath==1.0.1
lxml==4.9.2
packaging==23.0
psycopg2==2.9.5
python-dateutil==2.8.2
pytz==2022.7.1
redshift-connector==2.0.910
requests==2.28.2
s3transfer==0.6.0
scramp==1.4.4
six==1.16.0
soupsieve==2.4
urllib3==1.26.14
```

**Comment by Brooke-white** [comment]
Hi @ajisaka ,

Thanks for opening this issue.  I'm not certain for the reason of this discrepancy, but have an inclination it has to do with limitations for bind parameters on Redshift server. If you're not familiar with "bind parameters", [this doc](https://use-the-index-luke.com/sql/where-clause/bind-parameters) provides a good overview. The difference in behavior you're seeing for the two statements is due to the underlying difference in how the statements are executed on Redshift server. 

```
         # This line does not raise any errors
        cur.execute(f'CREATE MATERIALIZED VIEW ok AS ({definition})'.replace('%s', '100'))
```
This statement is sent to Redshift server as the string `CREATE MATERIALIZED VIEW ok AS (SELECT * FROM sample WHERE age = 100)`. No bind parameters are sent.

```
        # BUT this line raises an error
        cur.execute(f'CREATE MATERIALIZED VIEW ng AS ({definition})', (100,))
```
This statement is sent to Redshift server as the string `CREATE MATERIALIZED VIEW ok AS (SELECT * FROM sample WHERE age = %s)`. A bind parameter of the integer `100` is sent separately. 

I'm inclined to think this issue has to do with limitations of bind parameter support as we see similar behavior with using bind parameters in subqueries for `UNLOAD` statements, #31. 

As for why this works with psycopg2, but not redshift-connector, I believe there is some difference in how psyopg2 sends statements + bind parameters to Redshift server that redshift-connector -- possibly the bind parameters are re-joined with the statement before being sent to server.

**Comment by ajisaka** [comment]
@Brooke-white 

> If you're not familiar with "bind parameters"

I think I understand the point.

> #31

Thank you. I understand the situation now.

I have decided to work around this problem by providing a function that properly quotes and embeds the value using `literal_quote` after all.

```python
def embed_values(cur: Cursor, query: str, values: Any) -> str:
    def quote(v: Any) -> str:
        if type(v) == int:
            return str(v)
        if type(v) == str:
            cur.execute('SELECT QUOTE_LITERAL(%s)', v)
            return cur._cur.fetchone()[0]
        raise Exception(f'Not supported: {type(v)}')

    if type(values) == tuple:
        return query % tuple(map(quote, values))

    if type(values) == dict:
        quoted = {k: quote(v) for k, v in values.items()}
        return string.Template(query).substitute(**quoted)

    raise Exception(f'Not supported: values={type(values)}')
```
