### ISSUE TITLE
cursor.write_dataframe() method does not respect paramstyle

### ISSUE THREAD

**Issue by mberlinger3** [aws/amazon-redshift-python-driver#149]
## Driver version
2.0.907

## Redshift version
Unknown

## Client Operating System
All

## Python version
3.9

## Table schema
N/A

## Problem description
`cursor.write_dataframe()` method does not respect paramstyle

this line should be replaced to utilize the style in paramstyle:
```placeholder: str = ", ".join(["%s"] * len(arrays[0]))```

**Comment by Brooke-white** [comment]
Hey @mberlinger3  -- thanks for opening this issue and identifying the line that needs a fix. Since you've correctly identified the solution, would you want to open a PR so you can receive accreditation for fixing this bug? More than happy to help that process along, or alternatively I can make the fix myself if you prefer. Just let me know.

**Comment by mberlinger3** [comment]
Sure i can submit a PR for it!

**Comment by Brooke-white** [comment]
sounds good -- thank you! :)

**Comment by Brooke-white** [comment]
release 2.0.911 includes a fix for this
