### ISSUE TITLE
redshift_connector.connect() issue

### ISSUE THREAD

**Issue by preston-brown-icf** [aws/amazon-redshift-python-driver#151]
## Driver version
2.0.910

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.47357

## Client Operating System
Amazon Linux 2
Linux 5.10.173-154.642.amzn2.x86_64

## Python version
Python 3.9.16

## Problem description

1. Expected behaviour:

Call to redshift_connector.connect() will return a connection.

2. Actual behaviour:

Call to redshift_connector.connect() returns 

ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips

3. Error message/stack trace:

```
Traceback (most recent call last):
  File "/blah/rds_vs_redshift/blah.py", line 63, in <module>
    main()
  File "/blah/rds_vs_redshift/blah.py", line 17, in main
    init()
  File "/blah/rds_vs_redshift/blah.py", line 25, in init
    redshift = get_redshift_connection()
  File "/blah/rds_vs_redshift/blah.py", line 43, in get_redshift_connection
    conn = redshift_connector.connect(
  File "/blah/.pyenv/versions/3.9.16/lib/python3.9/site-packages/redshift_connector/__init__.py", line 340, in connect
    return Connection(
  File "/blah/.pyenv/versions/3.9.16/lib/python3.9/site-packages/redshift_connector/core.py", line 708, in __init__
    self.message_types[code](self._read(data_len - 4), None)
  File "/blah/.pyenv/versions/3.9.16/lib/python3.9/site-packages/redshift_connector/core.py", line 1302, in handle_AUTHENTICATION_REQUEST
    md5(self.password + self.user).hexdigest().encode("ascii") + salt
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips
```

4. Any other details that can be helpful:

I'm on an AWS instance that is running in FIPS mode. 

```
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2k-fips  26 Jan 2017'
```
I think FIPS doesn't support md5 unless you set usedforsecurity to False.

## Reproduction code

```
import redshift_connector

conn = redshift_connector.connect(
    host='any-value',
    port=1000,
    user='any-value',
    password='any-value',
    database='any-value'
)
```

**Comment by Brooke-white** [comment]
Hi @preston-brown-icf ,

Thank you for reaching out. You are correct in regards that this issue is due to FIPS not supporting MD5 and redshift-connector using MD5.

The LOC that raises this exception, 1302 of core.py, pertains to redshift-connector's handling Redshift server's "AuthenticationRequest" message. This line executed because Redshift server indicates that redshift-connector should send  the user's password using MD5 hash. This is likely due to how this user's password was configured upon creation. [see AWS docs on `CREATE USER` here](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_USER.html). Likely `md5hash` was specified when creating this user.

Given the constraints, I see a few options for resolution
1. Provide `redshift-connector.connect()` a user/password for a user which does not use `md5hash` for the password. `sha256hash` is an alternative.
2. Use an AWS instance that does not run in FIPS mode (guessing this isn't very helpful/possible as you're likely running in FIPS for a reason, but figured I'd throw it out there)
3. Authenticate with Redshift in a different fashion, such as using IAM authentication. IAM authentication would improve overall security as database credentials would no longer be in the source code. We have some examples of how you can do this [in our tutorials](https://github.com/aws/amazon-redshift-python-driver/blob/master/tutorials/001%20-%20Connecting%20to%20Amazon%20Redshift.ipynb)
