### ISSUE TITLE
`convert_paramstyle` throwing error when parsing SQL with block comment containing `%` character

### ISSUE THREAD

**Issue by jialerchew** [aws/amazon-redshift-python-driver#156]
## Driver version
2.0.910

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.49788

## Client Operating System
macos monterey 12.6.2

## Python version
3.9.11

## Table schema
Irrelevant

## Problem description
`convert_paramstyle` method throws error when parsing SQL that has block comment with `%` character in it.
1. Expected behaviour: works when running on `dbt` and dbeaver. Hence it should also work in `redshift_connector`.
2. Actual behaviour: Threw error.
3. Error message/stack trace: `redshift_connector.error.InterfaceError: Only %s and %% are supported in the query.`
4. Any other details that can be helpful: After commenting using `--` instead, the query worked.

## Python Driver trace logs
```
Traceback (most recent call last):
  File "/Users/jialer.chew/Tools/ditto-dbt/.dbt_local_test/query.py", line 66, in <module>
    cur.execute(query)
  File "/Users/jialer.chew/.pyenv/versions/3.9.11/envs/py_3.9.11_dbt_1.2_test/lib/python3.9/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/Users/jialer.chew/.pyenv/versions/3.9.11/envs/py_3.9.11_dbt_1.2_test/lib/python3.9/site-packages/redshift_connector/core.py", line 1622, in execute
    statement, make_args = cache["statement"][operation] = convert_paramstyle(cursor.paramstyle, operation)
  File "/Users/jialer.chew/.pyenv/versions/3.9.11/envs/py_3.9.11_dbt_1.2_test/lib/python3.9/site-packages/redshift_connector/core.py", line 203, in convert_paramstyle
    raise InterfaceError("Only %s and %% are supported in the query.")
redshift_connector.error.InterfaceError: Only %s and %% are supported in the query.
```

## Reproduction code
```
c = redshift_connector.connect(....)
query = """
    EXPLAIN
    /* blabla
       something 100% with percent
    */
    SELECT 'hi'
"""
cur = c.cursor()
try:
    cur.execute(query)
except socket.timeout as err:
    print(print_header + "30 seconds timeout. There might be congestion in Redshift!")
    print_results = False
except redshift_connector.error.ProgrammingError as err:
    err_type, err_obj, traceback = sys.exc_info()
    line_num = traceback.tb_lineno
    print(print_header + "Syntax error!\nERROR:", err)
    print_results = False

if print_results:
    # print(cur.fetchall())
    print(print_header + "Run successful!")

cur.close()
c.close()
```

**Comment by dbeatty10** [comment]
### Underlying issue

I believe the underlying issue is that [`convert_paramstyle`](https://github.com/aws/amazon-redshift-python-driver/blob/910be71314229e5b2febc60ddf8b8bcc992ea5f0/redshift_connector/core.py#L138) used in `redshift_connector` does not support [multiline comments](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS).

It does not support [dollar-quoted string constants](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS:~:text=4.1.2.4.-,Dollar%2DQuoted%20String%20Constants,-While%20the%20standard) either (as mentioned [here](https://github.com/dbt-labs/dbt-redshift/issues/441#issuecomment-1562070178)).

Without having checked either way, I'd suspect [`pg8000`](https://github.com/tlocke/pg8000/blob/f751b94a910975fd2e551814b7395336a5153cc8/pg8000/dbapi.py#L245) would have the same issues (since that is where `convert_paramstyle` originally came from). If it is already fixed in `pg8000`, then its solution might be adopted into `redshift_connector`. If not, then the eventual fix should be submitted to `pg8000` as well.

### Suggested path forward

Support both multiline comments and dollar-quoted string constants within `convert_paramstyle`.

#### Dollar-quoted string constants
Here's some code that roughly matches the coding style of [`convert_paramstyle`](https://github.com/aws/amazon-redshift-python-driver/blob/910be71314229e5b2febc60ddf8b8bcc992ea5f0/redshift_connector/core.py#L138) and _might_ be able to be merged into the existing implementation within `redshift_connector` to add handling for dollar-quoted string constants:

<details>
<summary>Code</summary>

`dollar_quoting.py`
```python
import typing


def convert_paramstyle(style: str, query) -> typing.Tuple[str, typing.Any]:

    OUTSIDE: int = 0  # outside quoted string
    INSIDE_SQ: int = 1  # inside single-quote string '...'
    INSIDE_QI: int = 2  # inside quoted identifier   "..."
    INSIDE_ES: int = 3  # inside escaped single-quote string, E'...'
    INSIDE_PN: int = 4  # inside parameter name eg. :name
    INSIDE_CO: int = 5  # inside inline comment eg. --
    INSIDE_DQ: int = 6  # inside dollar-quoted tag eg. $tag$ inside $tag$
    OPENING_DQ: int = 7  # opening a dollar-quoted tag eg. $tag$
    CLOSING_DQ: int = 8  # closing a dollar-quoted tag eg. $tag$ inside $tag$

    string_constant: str = ""  # TODO - remove
    starting_tag: str = ""
    closing_tag: str = ""
    output_query: typing.List[str] = []
    state: int = OUTSIDE

    for i, c in enumerate(query):
        if state == OUTSIDE:
            if c == "$":
                # starting tag for a dollar-quoted string constant
                output_query.append(c)
                state = OPENING_DQ
                starting_tag = ""
            else:
                output_query.append(c)
        elif state == OPENING_DQ:
            if c == "$":
                # end of a tag for a dollar-quoted string constant
                # and start of the actual string constant
                output_query.append(c)
                state = INSIDE_DQ
            else:
                output_query.append(c)
                starting_tag += c
        elif state == INSIDE_DQ:
            string_constant += c  # TODO - remove
            if c == "$":
                # potential closing tag for a dollar-quoted string constant
                output_query.append(c)
                state = CLOSING_DQ
            else:
                output_query.append(c)

        elif state == CLOSING_DQ:
            string_constant += c  # TODO - remove
            if c == "$" and closing_tag == starting_tag:
                # end of a closing tag for a dollar-quoted string constant

                # TODO - remove the next 3 lines - only for demo purposes
                string_constant = string_constant[:-(len(closing_tag) + 2)]
                print(f"string_constant: {string_constant}")
                string_constant = ""

                output_query.append(c)
                closing_tag = ""
                state = OUTSIDE
            else:
                output_query.append(c)
                closing_tag += c

                if not starting_tag.startswith(closing_tag):
                    # failed potential closing tag
                    state = INSIDE_DQ
                    closing_tag = ""

        else:
            output_query.append(c)

    return "".join(output_query)


query = "$$Dan's cats$$ $<tag>$Dianne's $$horse$$ $<tag$ $<tagg $<tag> $ $<tag>$ $animal$ Dani's dog $animal$"
result  = convert_paramstyle('faux style', query)
print(result)
```

```shell
python dollar_quoting.py
```

```
$ python dollar_quoting.py

string_constant: Dan's cats
string_constant: Dianne's $$horse$$ $<tag$ $<tagg $<tag> $ 
string_constant:  Dani's dog 

$$Dan's cats$$ $<tag>$Dianne's $$horse$$ $<tag$ $<tagg $<tag> $ $<tag>$ $animal$ Dani's dog $animal$
```
</details>

### Alternative solutions
Skipping bind parameters when the user doesn't pass them to `.execute()` would surely cut down on occurrences of this error. But I'm guessing it wouldn't eliminate them since users should be able to use multiline comments in combination with bind parameters as well. Hence the suggested path forward above.

**Comment by Brooke-white** [comment]
release 2.0.911 includes a fix for this, thank you for your patience
