### ISSUE TITLE
Incorrect buffer size calculation leads to failed query execution

### ISSUE THREAD

**Issue by renebrandel** [aws/amazon-redshift-python-driver#16]
## Driver version
2.0.872

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.19628

## Client Operating System
Mac OS 10.15.7

## Python version
Python 3.8.2

## Problem description
1. Expected behaviour: No errors when executing a query.
2. Actual behaviour: Errors out because of a buffer size miscalculation near core.py:900
3. Error message/stack trace:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/redshift_connector/core.py", line 946, in execute
    ps = cache["ps"][key]
KeyError: ("REDACTED_QUERY", ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(pbi.actives('2021-01-02'))
  File "/Users/renbran/Projects/metrics_test/DataSources.py", line 74, in actives
    return self.execute_query(query)
  File "/Users/renbran/Projects/metrics_test/DataSources.py", line 15, in execute_query
    cursor.execute(query)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/redshift_connector/cursor.py", line 162, in execute
    self._c.execute(self, operation, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/redshift_connector/core.py", line 1016, in execute
    self.handle_messages(cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/redshift_connector/core.py", line 1169, in handle_messages
    self.message_types[code](self._read(data_len - 4), cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/redshift_connector/core.py", line 901, in handle_ROW_DESCRIPTION
    temp: int = h_unpack(data, idx)[0]
struct.error: unpack_from requires a buffer of at least 40 bytes for unpacking 2 bytes at offset 38 (actual buffer size is 38)
```
4. Any other details that can be helpful:
- If I manually prepend the line 900 to with `idx -=6`, the query executes successfully. This let's me think that the buffer size calculation seems to be off.

## Python Driver trace logs
See above.

## Reproduction code
```python
 # Query is redacted for confidentiality
  def execute_query(self, query):
      cursor: redshift_connector.Cursor = self.conn.cursor()
      cursor.execute(query)
      result: tuple = cursor.fetchone()
      return result[0]
```

**Comment by Brooke-white** [comment]
Hey Rene,

Thanks for reaching out regarding this issue. I'll take a look into it and share my findings.

**Comment by Brooke-white** [comment]
There is an intentionally undocumented parameter for `redshift_connector.connect(...)`, `client_protocol_version`. Passing `client_protocol_version=0` should provide a work around for the time being.

**Comment by Brooke-white** [comment]
A fix will be provided in the next release to resolve this issue, for now the above workaround is the suggested.

**Comment by Brooke-white** [comment]
The recommendation for resolving this issue is to upgrade the cluster version.  See [Amazon Redshift Maintenance Forum Announcements](https://forums.aws.amazon.com/forum.jspa?forumID=155&start=0) for information about available Amazon Redshift cluster versions, and their features, improvements, and fixes. 

If updating the cluster version does not fit your use case, the above work around will resolve the issue seen here.

**Comment by glqstrauss** [comment]
We experienced this issue recently. Everything works fine on local machine (mac), has buffer error in container (linux). Resolving it was a pain, so if anyone else experiences the issue, hope this helps.

1. We had to modify linux keepalive options on the redshift connection's socket:
```python
if sys.platform == "linux":
    conn._usock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 60)  # default is two hours
    conn._usock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 60)
    conn._usock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 10)
```
(You could also modify the defaults on the image with sysctl, depending on whether you want all your sockets to be chattier or not...)

2. Additionally, we had to upgrade our docker base image from `python:3.10.9-buster` to `python:3.10.9-bullseye`. I'm not familiar enough with linux networking to understand why updating the socket keepalive options didn't work with `buster`/whether some setting can have been changed with `buster` instead of changing the OS version.

Details:
* Client OS: Debian Linux via `python:3:10.9-buster` (then `-bullseye`)
* Driver version: 2.0.910
* Redshift Cluster version: 1.0.46987

**Comment by Brooke-white** [comment]
Hi @glqstrauss , thank you for sharing your findings. This is extremely helpful to the Redshift team + redshift-connector users.

**Comment by sr-murthy** [comment]
Unfortunately I have the same issue. Running a Panoply query for a sizable dataset (of around 200 MB) in iPython using `redshift_connector` gives me:
```
struct.error: unpack_from requires a buffer of at least 46 bytes for unpacking 4 bytes at offset 42 (actual buffer size is 29)
```
This was after using `client_protocol_version=0` in the call. I'm using Python 3.9.6 and iPython 8.13.2.
