### ISSUE TITLE
SAMLAssertion interface error

### ISSUE THREAD

**Issue by AlexVielfaure** [aws/amazon-redshift-python-driver#18]
Hi, 

I am trying to use the redshift_connector with IAM credentials but when I put all the parameters and run the redshift_connector.connect function I get the following interface error : Failed to retrieve SAMLAssertion. 

I am using 'PingCredentialsProvider'

Thanks !

**Comment by AlexVielfaure** [comment]
I was able to resolve this issue by changing some line of code. Not sure if it case specific but if anyone comes across a similar issue  I can share the change I made.

**Comment by Brooke-white** [comment]
Hi @AlexVielfaure ,

Could you share the change you made to resolve this issue as well as the version of `redshift_connector` where this issue is seen?

Thanks

**Comment by AlexVielfaure** [comment]
Hi Brooke, 

I am using the 2.0.873 version of the connector. I was facing this issue with the PingCredentialsProvider. I changed a line of code in the 'redshift_connector\plugin\ping_credentials_provider.py' file. 

The URL in line 91 was giving me an expired page. I changed the line to (which is the URL that was used line 31):
url: str = "https://{host}:{port}/idp/startSSO.ping?PartnerSpId={sp_id}".format(host=self.idp_host, port=str(self.idpPort), sp_id=self.partner_sp_id)

Thanks !

**Comment by Brooke-white** [comment]
Thank you for the additional information, I will look into this and provide an update with my findings.

**Comment by Brooke-white** [comment]
1. If you clear the web browser cookies does the issue persist?
2. Is this issue occurring consistently?
3. Which identity provider are you using? PingOne? PingFederate?
4.

**Comment by Brooke-white** [comment]
Hey @AlexVielfaure ,

Are you using PingFederate or PingOne as your identity provider? 

I ask because if you are using PingOne, you will want to use `BrowserSamlCredentialsProvider`. `PingCredentialsProvider` is intended for use with PingFederate. Adding more documentation regarding identity provider plugins is a work in progress.

For PingOne there are steps detailed in this AWS blog for [Federating single sign-on access to your Amazon Redshift cluster with PingIdentity](https://aws.amazon.com/blogs/big-data/federating-single-sign-on-access-to-your-amazon-redshift-cluster-with-pingidentity/). These steps should be inline with what is required for setting up PingOne with `redshift_connector`.

If PingOne is the identity provider you are using, let me know if you run into any issues with the setup. If not, I will continue looking into this issue.

**Comment by Brooke-white** [comment]
closing this as I haven't heard back, please re-open if you are still experiencing issues.

**Comment by AlexVielfaure** [comment]
Hi Brooke, 

Sorry for not responding. Had a lot on my plate. Just wanted to let you know that this is still an issue. Thanks
