### ISSUE TITLE
Executing multi statement queries

### ISSUE THREAD

**Issue by ismailsimsek** [aws/amazon-redshift-python-driver#21]
is it possible to run multi statement sql queries? 
or is it possible to set this parameter `allowMultiQueries=true` to allow multi statements?

```python
query = 'create table ...; insert .. ; delete ...insert ;'
with self._db_connection.cursor() as curr:
    curr.execute(query)
```

currently running multi statement queries failing with following error

```
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '2724', 'R': 'exec_parse_message'}
```

related to #13

**Comment by Brooke-white** [comment]
Hey @ismailsimsek ,

At this time this functionality is not supported in `redshift_connector` because prepared statements are always used for execution.

You could use an approach similar to shown below:
```python
query = 'create table ...; insert .. ; delete ...insert ;'
queries = query.split(';')
with self._db_connection.cursor() as curr:
    for q in queries:
      curr.execute(q)
```

If the approach poses above doesn't help, providing some more details about your use case either in this issue or directly to the Amazon Redshift Driver team via redshift-drivers[at]amazon.com could help us determine prioritization for this issue internally.

As a side note, our [Amazon Redshift JDBC Driver](https://github.com/aws/amazon-redshift-jdbc-driver) supports multiple queries, though we have seen many customers opt to disable this functionality as it poses a security risk (i.e. SQL injection).
