### ISSUE TITLE
redshift-connector does not work as expected or reliably and the docs are a mess

### ISSUE THREAD

**Issue by els-pnw** [aws/amazon-redshift-python-driver#33]
I have created a connection using redshift-connector and I'm finding a number of possible issues. All I'm trying to do is setup a (reliable) function within my library that will create the cursor and execute the passed sql statement with autocommit enabled, we need to support at a minimum delete from and select from.

Connection setup:
```
conn = redshift_connector.connect(
    host=db_host,
    port=5439,
    database=db_name,
    user=db_user,
    password=db_pass
)
```
Note that in my library we use the @property decorator as follows:
```
@property
def conn(self):
    conn = redshift_connector.connect(
    ...
    )
```
Then when I attempt to follow the instructions here https://pypi.org/project/redshift-connector/ to run sql statements I encounter a variety of problems. In fact, about the only thing that I have seen work is select.

For example,
```
cursor = conn.cursor() 
res = cursor.execute("delete from schema.table where col = "val" 
res.close()
Results in nothing being deleted.
```
Then if I do
```
conn.autocommit = True
cursor = conn.cursor() 
res = cursor.execute("delete from schema.table where col = "val" 
res.close()
```
I get 3 locks created in Redshift, ShareRowExclusiveLock granted:True, AccessShareLock granted:True, ShareRowExclusiveLock granted:False and the execute statement hangs until I delete the locks. After deleting the locks, depending whether or not I terminate the right lock the execute statement will either complete successfully or it will error out.

Terminating all the locks results in nothing getting deleted on a follow up execution.

My current theory is that redshift-connector is not creating and removing locks correctly or efficiently.

As a side note, I have found that I am not able to swap in sqlalchemy-redshift, the latest version of awswrangler seems to expect redshift-connector for some unknown reason (not sure why someone thought it would be fun to reinvent the wheel). Using sqlalchemy postgresql+psycopg2 or redshift+psycopg2 results in an AttributeError related to autocommit. It would also seem that awswrangler doesn't support or work with sqlalchemy's execution_options(autocommit=True).

I'll also add that the pypi page suggests that there's a **redshift_connector** tag, there's not.

I would appreciate any help here, if someone knows how to get sqlalchemy to work with awswrangler that would be preferred.

**Comment by Brooke-white** [comment]
Hi @els-pnw ,

Thank you for reaching out and providing feedback. I will pass your thoughts along to the team.

Please provide the following information so I can further look into this issue:

1. Driver version
2. Redshift version
3. Client Operating System
4. Python version


> Then when I attempt to follow the instructions here https://pypi.org/project/redshift-connector/ to run sql statements I encounter a variety of problems. In fact, about the only thing that I have seen work is select.
> For example,
> cursor = conn.cursor() 
> res = cursor.execute("delete from schema.table where col = "val" 
> res.close()
> Results in nothing being deleted.

The behavior you describe, nothing being deleted, is expected in this case because `autocommit` is disabled by default per DBAPI specification.

Regarding the behavior you're experiencing with hanging and locks, I have attempted to reproduce the issue described using the code shown below and am unable to reproduce. Please note that single quotes should be used within your delete statement e.g. `delete from schema.table where col = 'val'`. Please let me know if this example works for you. If this reproduction is not representative of your use case, let me know.

```python
# python 3.9
# redshift version 1.0.26073
# redshift_connector version 2.0.878
import redshift_connector

class SomeClass:
    @property
    def conn(self):
        return redshift_connector.connect(
            host="XXX.redshift.amazonaws.com",
            database='XXX',
            user='XXX',
            password='XXX',
        )

    def my_method(self):
        with self.conn as conn:
            conn.autocommit = True
            with conn.cursor() as cursor:
                cursor.execute("create table book(bookname varchar,author varchar)")
                cursor.executemany("insert into book (bookname, author) values (%s, %s)",
                                   [
                                       ('One Hundred Years of Solitude', 'Gabriel García Márquez'),
                                       ('A Brief History of Time', 'Stephen Hawking')
                                   ]
                                   )
                print("Table contents after insertion:")
                cursor.execute("select * from book")
                print(cursor.fetchall())

                cursor.execute("delete from book where bookname = 'One Hundred Years of Solitude'")

                print("Table contents after deletion:")
                cursor.execute("select * from book")
                print(cursor.fetchall())

issue33 = SomeClass()

issue33.my_method()
```

```bash
Table contents after insertion:
(['One Hundred Years of Solitude', 'Gabriel García Márquez'], ['A Brief History of Time', 'Stephen Hawking'])
Table contents after deletion:
(['A Brief History of Time', 'Stephen Hawking'],)

```

Regarding documentation for the project, I completely hear you -- there is a lot of room for improvement here. If you could provide specific feedback on what improvements you would like to see in our docs I can pass this along to the team and we will work to add it to the repo.

Regarding sqlalchemy and awswrangler issues, I'd recommend sharing your feedback with the respective projects as it isn't my area of expertise. My one thought there would be to ensure you're passing the correct Connection object to awswrangler `copy` (does it want the sqlalchemy Connection object or the DBAPI Connection object (e.g. `psycopg2`)?).

As for why awswrangler integrated with redshift_connector, redshift_connector provides awswrangler users with Amazon Redshift specific functionality such as IAM authentication and datatype support. We work closely with the Amazon Redshift server team in order to ensure redshift_connector supports server-side changes before they are released to the public.

**Comment by Brooke-white** [comment]
For sqlalchemy, this link maybe helpful: https://docs-sqlalchemy.readthedocs.io/ko/latest/faq/connections.html#how-do-i-get-at-the-raw-dbapi-connection-when-using-an-engine

**Comment by els-pnw** [comment]
Thank you @Brooke-white  for the pointers and I apologize that I forgot to include the part of my code where I am setting `conn.autocommit=True`.    To answer your questions:

- Driver version
`select version()` returns: PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.26365
- Redshift version
See previous
- Client Operating System
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
- Python version
Python 3.8.3
>>> redshift_connector.__version__
'2.0.878'
>>> sqlalchemy.__version__
'1.3.23'

In the mean time I've also found that I had a number of stale sessions out there (on Redshift) and have since cleared those.  I will do some more testing today and update accordingly.

As for sqlalchemy, I understand how to use it and set commit etc... The problem is it seems AWSWrangler no longer supports sqlalchemy.

**Comment by Brooke-white** [comment]
Hi @els-pnw ,

Were you able to resolve the hanging statement issue?

As a side note, the Amazon Redshift drivers team is working to develop a sqlalchemy dialect built on top of redshift-connector. We'd love to hear any feedback you can share about the features and functionalities you and your team would find useful in this product.

**Comment by igorkaludjer** [comment]
We are also having the same issue with locks (transaction isolation) and had to revert to psycopg2

**Comment by Brooke-white** [comment]
Hi @igorkaludjer , Could you share more about when the issues with locks are occurring? Is multithreading being used? Long running transactions?

**Comment by igorkaludjer** [comment]
No multithreading, but one of the transactions is long running.

**Comment by Brooke-white** [comment]
@igorkaludjer ,

Thank you for those details. I will dive into this issue and report back with my findings, though in the meantime I will point you towards [this issue](https://github.com/tlocke/pg8000/issues/16) opened against pg8000, which redshift_connector is based upon, which provides some measures that could be taken to prevent this behavior.

**Comment by Brooke-white** [comment]
Small update, I've been unable to reproduce this issue locally. If anyone can provide a repro I can continue to investigate this behavior.

**Comment by Brooke-white** [comment]
Official docs have been released for `redshift_connector` they are available [here](https://docs.aws.amazon.com/redshift/latest/mgmt/python-redshift-driver.html).
