### ISSUE TITLE
404 Error when using OktaCredentialsProvider

### ISSUE THREAD

**Issue by kylemcleland-fanduel** [aws/amazon-redshift-python-driver#53]
## Driver version
3.8

## Redshift version
`PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.29551`

## Client Operating System
Mac, ran locally

## Python version
3.8

## Table schema
n/a

## Problem description
1. Trying to replicate a JDBC connection in Python, to create a connection object.
2. Running following code to connect to Redshift doesn't work, results in 404 error (see bottom section)

However, the supplying the same information in a JDBC client (e.g. PyCharm/Datagrip) results in a successful connection. After reviewing the code vs the JDBC connection several times, I am certain there is not a typo in any of the parameters in the python code.

## Reproduction code
```
import redshift_connector

gdp_conn = redshift_connector.connect(
    iam=True,
    database="<<db name>>",
    cluster_identifier="<<cluster name>>",
    credentials_provider='OktaCredentialsProvider',
    user="<<redacted>>@<<domain>>",
    password="<<redacted>>",
    idp_host="<<idp_host>>",
    app_id="myappidstring",
    role_arn="arn:aws:iam::<<accountid>>:role/<<rolename>>"
)
```

```
redshift_connector.error.InterfaceError: 404 Client Error: Not Found for url: https://<<idp_host>>/home/amazon_aws_redshift/<<app_id>>?onetimetoken=<<redacted>>
```

**Comment by Brooke-white** [comment]
Hi @kylemcleland-fanduel ,

Thank you for reaching out regarding this issue. My recommendation would be the following
- ensure you're using the latest release of redshift_connector
- enable debug logging using the [python logging library](https://docs.python.org/3/library/logging.html) and review the logs relevant to the following keywords: Okta, SAML. **Please be aware the contents of the logs will contain information specific to your Okta configuration**.

As you mentioned this issue is not seen with the Amazon JDBC driver, and the same information is provided to establish the connection, I would guess there may be some issue with the Okta session token or URL used for authenticating with Okta.

Looking to the [JDBC source code](https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/plugin/OktaCredentialsProvider.java#L153) which builds the URL containing the Okta session token, it appears inline with the [redshift_connector implementation](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/plugin/okta_credentials_provider.py#L94), except for the URL encoding of the Okta `app_name`. 

While this is a bug in redshift_connector, I don't believe it is the cause of this issue unless the Okta `app_name` is something which would require url encoding -- which `amazon_aws_redshift` would not.

A quick way to check this is to plug your `app_name` into a site [like this](https://www.urlencoder.org/) which will allow you to url encode text.

If this is the issue at hand, a workaround for the time being would be to url encode the `app_name` before passing it to `redshift_connector.connect(...)` method.

Otherwise, my guess would be this has to do with the Okta session token -- for which reviewing the logs will provide some insight.

Additionally, for redshift_connector one additional parameter to `redshift_connector.connect(...)`  is required, `region`. This is used for establishing a `boto3` session to retrieving temporary IAM credentials to access the given cluster.

**Comment by kylemcleland-fanduel** [comment]
@Brooke-white thanks for the response. Apologies for the delay in getting back on this. 

It looks like the issue was with my app_id. The string looked like this 'bunchofcharacters/morecharacters' from the Okta portal. Weirdly I can log in using a JDBC client passing just 'bunchofcharacters' but adding the full string seems to get me further along in the connection phase. I'm going to close this issue.
