### ISSUE TITLE
Incorrect Output when query has a subquery

### ISSUE THREAD

**Issue by donde-esta-la-biblioteca** [aws/amazon-redshift-python-driver#70]
## Driver version
Latest version: v2.0.900

## Redshift version
![Redshift Version](https://user-images.githubusercontent.com/79408609/145130236-1edf48f9-d8eb-4c87-8761-520e4e932d7b.PNG)

## Client Operating System
Win10 Enterprise
Version: 10.0.19042 Build 19042

## Python version
3.9.7

## Table schema
[Table Schema.txt](https://github.com/aws/amazon-redshift-python-driver/files/7645985/Table.Schema.txt)

## Problem description
Using redshift_connector produces incorrect outputs.
The initial query was initially created in SQL Workbench /J. 
The query initially was a SELECT with a subquery SELECT. 
It was re-written with a WITH block to see if that helped with the incorrect output. It did not.
I tried the same query with psycopg2 - worked perfectly. (see pictures attached)

1. Expected behaviour:
![psycopg2 - correct output](https://user-images.githubusercontent.com/79408609/144525662-d8b1980b-e2c4-405a-a164-92d2af58386e.PNG)

2. Actual behaviour:
![Bugged redshift_connector](https://user-images.githubusercontent.com/79408609/144525705-cc9674d7-7b7d-44c4-aef0-721216edd0b9.PNG)

4. Any other details that can be helpful:

## Reproduction code
See attached pics. Obviously, I had to redact or hide the Redshift server and user login credentials... and some other potentially sensitive information.

**Comment by Brooke-white** [comment]
Hey @donde-esta-la-biblioteca ,

Thanks for reaching out regarding this issue. We will investigate and respond with our findings shortly.

**Comment by Brooke-white** [comment]
Hi @donde-esta-la-biblioteca ,

As a temporary measure, please pass `client_protocol_version=1` to the `redshift_connector.connect()` method. 

Additionally, could you please share the Redshift server version in which this issue is seen. This can be retrieved by executing `select version();`.

**Comment by donde-esta-la-biblioteca** [comment]
Hi @Brooke-white,

I've updated the original ticket with the Redshift server version.

The temporary measure worked perfectly. 

Thanks!

**Comment by galmog** [comment]
Hi,
I am experiencing the same issue with negative results when running a subquery. The temporary measure suggested doesn't fix the problem.

**Comment by Brooke-white** [comment]
Hey @galmog , could you please open a new issue including the version of redshift-connector you are using as well as the server version. Also please explain what is meant by "negative result"? What Redshift datatype is this behavior seen for?

**Comment by galmog** [comment]
## Driver version
Latest version: v2.0.900

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38214

## Client Operating System
Ubuntu 20.04.4 

## Python version
3.9.7

I am hesitant to include full screenshots due to sensitive information. My query does contain a subquery and these are the results I am getting. By negative results I meant I am getting negative numbers where they don't make sense, and I know for sure that they should not be negative. Some of the numbers are correct and others are wrong. I've cropped the last column in the pictures but these are corresponding rows.

1. Expected behaviour from redash:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/46827551/168463316-f03f633e-a0ea-42fe-86eb-e208984106e7.png">

2. Actual behaviour:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/46827551/168463305-498d4c51-ccdd-4709-9a43-341ecbbc7bfa.png">

**Comment by Brooke-white** [comment]
Hi @galmog ,

Thank you for providing these details. I looked into this issue on my cluster, having server version 1.0.38361, and was unable to reproduce. This could be due to the test I am using (included below) or a server change that resolved this issue.

Could you please provide the following to assist my investigation?
1. Column definition for `daily_avg` e.g. `decimal(32,3)
2. Output showing actual and expected value for `daily_avg` column. A way to achieve this is doing some query like `select daily_avg as actual, cast(daily_avg as varchar) as expected`. This can help me identify which values are seeing issue and where the issue originates (either the driver due to conversion error, or the server sending an incorrect value)
3. Has the server version for your cluster upgraded? If so, please provide the new version. Also, please confirm if the issue still occurs.

How I am trying to repro this issue:

```python
        for test_val in ('1.0', '1.23', '12.3', '123.45', '123456789.89', '-1.0', '123.34', '9999999.777'):
            cursor.execute("select cast(cast(%s as decimal(32,3)) as varchar) as expected, cast(expected as decimal(32,3)) as actual;", (test_val,))
            print(cursor.fetchone())
```

```
['1.000', Decimal('1.000')]
['1.230', Decimal('1.230')]
['12.300', Decimal('12.300')]
['123.450', Decimal('123.450')]
['123456789.890', Decimal('123456789.890')]
['-1.000', Decimal('-1.000')]
['123.340', Decimal('123.340')]
['9999999.777', Decimal('9999999.777')]
```
